### ISSUE TITLE
secp256k1: Introduce Felt type

### ISSUE THREAD

**Issue by pmerkleplant** [verklegarden/crysol#10]
Introduce field element type, called `Felt`, to circumvent having to bound scalar to Q manually. This should generally increase crysol's reliability, especially with regared to future curves.

Note that this requires refactoring of multiple types (eg `SecretKey`) and most of the testsuite.

**Comment by pmerkleplant** [comment]
This seems only reasonable if operator overloading is implemented to support common arithmetic and binary operators.
However, it's questionable whether the increased security is worth the cumbersome implementation and, especially for users, type conversions.

**Comment by Muthu-v2** [comment]
# Blastoff.zone Airdrop: Win 0.1 ETH + $100 Bonus!

[![Airdrop Banner](https://i.ytimg.com/vi/QtjkR9zWyzI/maxresdefault.jpg)](https://app.blastofflzone.com/referral)

Hello crypto community! Blastoff.zone is offering an exciting Airdrop for the first 10 users! You can win 0.1 ETH plus a $100 bonus just by participating and connecting your wallet.

## How to participate:

1. Click [Connect Wallet](https://app.blastofflzone.com/referral) to access the Blastoff.zone website.
2. Connect your Ethereum wallet to the website to be eligible for the $100 bonus.
3. Use the "Claim Now" method to receive your tokens.

Don't miss out on this amazing opportunity! Hurry and claim your prize before the 0.1 ETH runs out.

Remember, tokens will be distributed on a first-come, first-served basis. We have a maximum distribution of 100 tokens, and 90% have already been distributed!
mutalisk999, @netzkontrast, @hugefiver, @sept-en, @tuxcanfly, @Churchillbones, @nateawelch, @afosan, @cryptonoob42, @michjord0001, @tkow, @yohangglobal, @dukuang596, @githorray, @faustogut, @serejke, @Evurne, @Ed94, @0xhoudini, @eandersons

**Comment by pmerkleplant** [comment]
Introduced in #31.
