### ISSUE TITLE
Add on-chain operation to derive address from private key using ecrecover

### ISSUE THREAD

**Issue by StackOverflowExcept1on** [verklegarden/crysol#18]
```solidity
// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.16;

import {Secp256k1Arithmetic, Point, ProjectivePoint} from "./Secp256k1Arithmetic.sol";

contract MyContract {
    using Secp256k1Arithmetic for Point;
    using Secp256k1Arithmetic for ProjectivePoint;

    uint256 private constant _ADDRESS_MASK = 2 ** 160 - 1;

    // ~500k gas
    function deriveAddressSlow(uint256 privateKey) public view returns(address) {
        ProjectivePoint memory g = Secp256k1Arithmetic.G().toProjectivePoint();
        Point memory point = Secp256k1Arithmetic.mul(g, privateKey).intoPoint();
        address addr;
        assembly ("memory-safe") {
            addr := and(keccak256(point, 0x40), _ADDRESS_MASK)
        }
        return addr;
    }

    // ~4000 gas
    function deriveAddressFast(uint256 privateKey) public pure returns(address) {
        uint256 r = 0x79BE667EF9DCBBAC55A06295CE870B07029BFCDB2DCE28D959F2815B16F81798;
        uint256 m = 0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFEBAAEDCE6AF48A03BBFD25E8CD0364141;
        return ecrecover(0, 27, bytes32(r), bytes32(mulmod(privateKey, r, m)));
    }
}

```

**Comment by pmerkleplant** [comment]
This is a very interesting use-case and solution. Thanks for raising the issue!

Out of curiosity, could you provide a use-case for deriving an Ethereum address from a private key _onchain_? As you probably know for offchain we provide `sk.toPublicKey().toAddress()`, which uses the `vm.createWallet()` cheatcode.

**Comment by StackOverflowExcept1on** [comment]
> Out of curiosity, could you provide a use-case for deriving an Ethereum address from a private key *onchain*?

Ransomware based on smart contracts. Someone makes deposit to public key, and the other party can withdraw funds if give the correct private key.

**Comment by pmerkleplant** [comment]
> Ransomware based on smart contracts.

mmmhhh... Not sure what to answer on that tbh xD

> and the other party can withdraw funds if give the correct private key

So its about proving ownership/knowledge of a private key? Why not just let the owner do a normal tx directly?
Note that moving funds based on public input to a contract can easily be frontrun by bots. As soon as the private key hits the mempool the funds are basically free for all. Using a _very_ trusted relay or own block production is necessary.

**Comment by StackOverflowExcept1on** [comment]
> As soon as the private key hits the mempool the funds are basically free for all.

This is easy to work around via commit-reveal schemes: https://solidity-by-example.org/hacks/front-running/
